---
name: 'create release branch'
on:
  workflow_dispatch:

jobs:
  branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
        if: always()
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'github'
          email: 'digitaal-techniek@vpro.nl'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release branch with Maven
        run: |
          VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
          RELEASE_VERSION=`echo $VERSION | sed -r 's/-SNAPSHOT/.0-SNAPSHOT/'`
          DEVELOPMENT_VERSION=`echo $VERSION | gawk 'match($1, /([0-9]+)\.([0-9]+)([\.-])(.*)/, a) {print a[1]"."(a[2]+1)a[3]a[4]}'`
          mvn  -DupdateBranchVersions=true -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${DEVELOPMENT_VERSION} release:branch
