---
name: build pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '7.6.1'
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -fae -DskipITs=false -Dinteg.cluster.name=docker-elasticsearch -B  package
      - name: Publish to codecov
        run: bash <(curl -s https://codecov.io/bash)
        continue-on-error: true
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
